## Kaiburr Task 6. Data Science example.

## Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy.stats import zscore
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [23]:
df=pd.read_csv("D:\datasets\complaints.csv")

In [48]:
df1=pd.read_csv("D:\datasets\complaints.csv")

In [24]:
df.head()

Date received                                            Product  \
0    2023-09-04  Money transfer, virtual currency, or money ser...   
1    2023-09-06                                    Debt collection   
2    2023-09-06                        Checking or savings account   
3    2023-09-07                                    Debt collection   
4    2023-09-13  Credit reporting or other personal consumer re...   

                        Sub-product  \
0          Mobile or digital wallet   
1                        Other debt   
2  Other banking product or service   
3                  Credit card debt   
4                  Credit reporting   

                                               Issue  \
0  Trouble accessing funds in your mobile or digi...   
1                  Attempts to collect debt not owed   
2                                Managing an account   
3                              Communication tactics   
4               Incorrect information on your report   

                                      Sub-issue Consumer complaint narrative  \
0                                           NaN                          NaN   
1             Debt was result of identity theft                          NaN   
2                     Problem accessing account                          NaN   
3                    Frequent or repeated calls                          NaN   
4  Old information reappears or never goes away                          NaN   

                             Company public response  \
0                                                NaN   
1  Company believes the complaint is the result o...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                             Company State ZIP code Tags  \
0               Paypal Holdings, Inc    NC    27587  NaN   
1       CCS Financial Services, Inc.    FL    33032  NaN   
2  CAPITAL ONE FINANCIAL CORPORATION    LA    70117  NaN   
3  PORTFOLIO RECOVERY ASSOCIATES INC    PA    150XX  NaN   
4                      EQUIFAX, INC.    FL    33805  NaN   

  Consumer consent provided? Submitted via Date sent to company  \
0                        NaN           Web           2023-09-04   
1                        NaN           Web           2023-09-06   
2                        NaN           Web           2023-09-06   
3                        NaN           Web           2023-09-07   
4                        NaN           Web           2023-09-13   

      Company response to consumer Timely response? Consumer disputed?  \
0          Closed with explanation              Yes                NaN   
1          Closed with explanation              Yes                NaN   
2  Closed with non-monetary relief              Yes                NaN   
3  Closed with non-monetary relief              Yes                NaN   
4                      In progress              Yes                NaN   

   Complaint ID  
0       7493283  
1       7510657  
2       7510356  
3       7514982  
4       7537220

In [25]:
df.shape

(4065103, 18)

In [26]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [27]:
df.isnull().sum()

Date received                         0
Product                               0
Sub-product                      235291
Issue                                 0
Sub-issue                        716221
Consumer complaint narrative    2592900
Company public response         2184969
Company                               0
State                             43212
ZIP code                          30211
Tags                            3639919
Consumer consent provided?       901575
Submitted via                         0
Date sent to company                  0
Company response to consumer          5
Timely response?                      0
Consumer disputed?              3296745
Complaint ID                          0
dtype: int64

## Data Preprocessing

In [28]:
df["Product"].unique()

array(['Money transfer, virtual currency, or money service',
       'Debt collection', 'Checking or savings account',
       'Credit reporting or other personal consumer reports', 'Mortgage',
       'Credit card', 'Vehicle loan or lease',
       'Credit reporting, credit repair services, or other personal consumer reports',
       'Student loan',
       'Payday loan, title loan, personal loan, or advance loan',
       'Credit card or prepaid card', 'Consumer Loan', 'Prepaid card',
       'Bank account or service',
       'Payday loan, title loan, or personal loan',
       'Debt or credit management', 'Credit reporting', 'Payday loan',
       'Money transfers', 'Other financial service', 'Virtual currency'],
      dtype=object)

## Since there are multiple categories in each record separated by comma, They will be splitted and put in a separate column.

In [29]:
# Step 1: Determine the maximum number of sports in a single record
max_product_count = df['Product'].str.split(',').apply(len).max()

# Step 2: Split the 'sports_records' column into multiple columns
split_product = df['Product'].str.split(',', expand=True, n=max_product_count)

# Step 3: Fill in missing values with NaN
split_product = split_product.fillna("")

# Rename the columns if needed (e.g., sports_1, sports_2, ...)
split_product.columns = [f"issue_{i+1}" for i in range(max_product_count)]

# Concatenate the split DataFrame with the original DataFrame
df = pd.concat([df, split_product], axis=1)

# Drop the original 'sports_records' column
df.drop(columns=['Product'], inplace=True)

print(df)


        Date received                       Sub-product  \
0          2023-09-04          Mobile or digital wallet   
1          2023-09-06                        Other debt   
2          2023-09-06  Other banking product or service   
3          2023-09-07                  Credit card debt   
4          2023-09-13                  Credit reporting   
...               ...                               ...   
4065098    2015-02-21                               NaN   
4065099    2015-07-19                               NaN   
4065100    2022-06-16        Conventional home mortgage   
4065101    2022-04-26                     I do not know   
4065102    2022-08-15                  Checking account   

                                                     Issue  \
0        Trouble accessing funds in your mobile or digi...   
1                        Attempts to collect debt not owed   
2                                      Managing an account   
3                                    Commun

In [30]:
df.head()

Date received                       Sub-product  \
0    2023-09-04          Mobile or digital wallet   
1    2023-09-06                        Other debt   
2    2023-09-06  Other banking product or service   
3    2023-09-07                  Credit card debt   
4    2023-09-13                  Credit reporting   

                                               Issue  \
0  Trouble accessing funds in your mobile or digi...   
1                  Attempts to collect debt not owed   
2                                Managing an account   
3                              Communication tactics   
4               Incorrect information on your report   

                                      Sub-issue Consumer complaint narrative  \
0                                           NaN                          NaN   
1             Debt was result of identity theft                          NaN   
2                     Problem accessing account                          NaN   
3                    Frequent or repeated calls                          NaN   
4  Old information reappears or never goes away                          NaN   

                             Company public response  \
0                                                NaN   
1  Company believes the complaint is the result o...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                             Company State ZIP code Tags  ... Submitted via  \
0               Paypal Holdings, Inc    NC    27587  NaN  ...           Web   
1       CCS Financial Services, Inc.    FL    33032  NaN  ...           Web   
2  CAPITAL ONE FINANCIAL CORPORATION    LA    70117  NaN  ...           Web   
3  PORTFOLIO RECOVERY ASSOCIATES INC    PA    150XX  NaN  ...           Web   
4                      EQUIFAX, INC.    FL    33805  NaN  ...           Web   

  Date sent to company     Company response to consumer Timely response?  \
0           2023-09-04          Closed with explanation              Yes   
1           2023-09-06          Closed with explanation              Yes   
2           2023-09-06  Closed with non-monetary relief              Yes   
3           2023-09-07  Closed with non-monetary relief              Yes   
4           2023-09-13                      In progress              Yes   

  Consumer disputed? Complaint ID  \
0                NaN      7493283   
1                NaN      7510657   
2                NaN      7510356   
3                NaN      7514982   
4                NaN      7537220   

                                             issue_1            issue_2  \
0                                     Money transfer   virtual currency   
1                                    Debt collection                      
2                        Checking or savings account                      
3                                    Debt collection                      
4  Credit reporting or other personal consumer re...                      

             issue_3 issue_4  
0   or money service          
1                             
2                             
3                             
4                             

[5 rows x 21 columns]

In [31]:
labcol=list(df.select_dtypes('object').columns)
labcol

['Date received',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'ZIP code',
 'Tags',
 'Consumer consent provided?',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Consumer disputed?',
 'issue_1',
 'issue_2',
 'issue_3',
 'issue_4']

In [32]:
#Columns with >=30%  missing values
dim=df.shape
thirtyper=dim[0]/3
delcolumns=[]
for i in df.columns:
  if(df[i].isnull().sum()>=thirtyper):
    delcolumns.append(i)

In [33]:
delcolumns

['Consumer complaint narrative',
 'Company public response',
 'Tags',
 'Consumer disputed?']

In [34]:
for i in delcolumns:
    df.drop(i,axis=1,inplace=True)

In [35]:
df.drop("Complaint ID",axis=1,inplace=True)

In [36]:
df.drop("ZIP code",axis=1,inplace=True)

In [37]:
df.drop("Company",axis=1,inplace=True)

In [38]:
labcol=list(df.select_dtypes('object').columns)
labcol

['Date received',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'State',
 'Consumer consent provided?',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'issue_1',
 'issue_2',
 'issue_3',
 'issue_4']

In [39]:
for i in labcol:
    df[i].fillna(value=df[i].mode()[0],inplace=True)

In [40]:
df.isnull().sum()

Date received                   0
Sub-product                     0
Issue                           0
Sub-issue                       0
State                           0
Consumer consent provided?      0
Submitted via                   0
Date sent to company            0
Company response to consumer    0
Timely response?                0
issue_1                         0
issue_2                         0
issue_3                         0
issue_4                         0
dtype: int64

## Date received and Date sent to the company will be processed in order to get the difference in days.

In [41]:
import pandas as pd

# Convert the date columns to datetime objects if they are not already
df['Date received'] = pd.to_datetime(df['Date received'])
df['Date sent to company'] = pd.to_datetime(df['Date sent to company'])

# Calculate the date difference in days and create a new column
df['date_difference_days'] = (df['Date sent to company'] - df['Date received']).dt.days

In [42]:
df.drop('Date received',axis=1,inplace=True)
df.drop('Date sent to company',axis=1,inplace=True)

In [47]:
labcol.remove('Date received')
labcol.remove('Date sent to company')

In [48]:
from sklearn.preprocessing import LabelEncoder
def lab(labcol):
  for i in labcol:
    df[i]=LabelEncoder().fit_transform(df[i])
lab(labcol)

In [49]:
df.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_1  \
0              5                             1                 1        9   
1              5                             1                 1        7   
2              5                             3                 1        1   
3              5                             3                 1        7   
4              5                             6                 1        6   

   issue_2  issue_3  issue_4  date_difference_days  
0        3        1        0                     0  
1        0        0        0                     0  
2        0        0        0                     0  
3        0        0        0                     0  
4        0        0        0                     0

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4065103 entries, 0 to 4065102
Data columns (total 13 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Sub-product                   int32
 1   Issue                         int32
 2   Sub-issue                     int32
 3   State                         int32
 4   Consumer consent provided?    int32
 5   Submitted via                 int32
 6   Company response to consumer  int32
 7   Timely response?              int32
 8   issue_1                       int32
 9   issue_2                       int32
 10  issue_3                       int32
 11  issue_4                       int32
 12  date_difference_days          int64
dtypes: int32(12), int64(1)
memory usage: 217.1 MB


In [51]:
df.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_1  \
0              5                             1                 1        9   
1              5                             1                 1        7   
2              5                             3                 1        1   
3              5                             3                 1        7   
4              5                             6                 1        6   

   issue_2  issue_3  issue_4  date_difference_days  
0        3        1        0                     0  
1        0        0        0                     0  
2        0        0        0                     0  
3        0        0        0                     0  
4        0        0        0                     0

In [52]:
data1=df.drop(['issue_2','issue_3','issue_4'],axis=1)
data2=df.drop(['issue_1','issue_3','issue_4'],axis=1)
data3=df.drop(['issue_1','issue_2','issue_4'],axis=1)
data4=df.drop(['issue_1','issue_2','issue_3'],axis=1)

In [53]:
data1.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_1  \
0              5                             1                 1        9   
1              5                             1                 1        7   
2              5                             3                 1        1   
3              5                             3                 1        7   
4              5                             6                 1        6   

   date_difference_days  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

In [54]:
data2.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_2  \
0              5                             1                 1        3   
1              5                             1                 1        0   
2              5                             3                 1        0   
3              5                             3                 1        0   
4              5                             6                 1        0   

   date_difference_days  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

In [55]:
data3.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_3  \
0              5                             1                 1        1   
1              5                             1                 1        0   
2              5                             3                 1        0   
3              5                             3                 1        0   
4              5                             6                 1        0   

   date_difference_days  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

In [56]:
data4.head()

Sub-product  Issue  Sub-issue  State  Consumer consent provided?  \
0           43    156        122     35                           0   
1           54     13         78     13                           0   
2           53     94        164     24                           0   
3           12     36        107     46                           0   
4           15     78        151     13                           0   

   Submitted via  Company response to consumer  Timely response?  issue_4  \
0              5                             1                 1        0   
1              5                             1                 1        0   
2              5                             3                 1        0   
3              5                             3                 1        0   
4              5                             6                 1        0   

   date_difference_days  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

## Softmax classifier

In [62]:
X1=data1.drop('issue_1',axis=1)
y1=data1['issue_1']
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.3,random_state=0)
softmax_model1 = LogisticRegression(multi_class='multinomial', solver='lbfgs')
softmax_model1.fit(X1_train, y1_train)

C:\Users\HRITHIK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [63]:
y_pred1 = softmax_model1.predict(X1_test)
print(y_pred1)

[5 5 5 ... 5 7 5]


In [64]:
X2=data2.drop('issue_2',axis=1)
y2=data2['issue_2']
X2_train,X2_test,y2_train,y2_test=train_test_split(X2,y2,test_size=0.3,random_state=0)
softmax_model2 = LogisticRegression(multi_class='multinomial', solver='lbfgs')
softmax_model2.fit(X2_train, y2_train)

C:\Users\HRITHIK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [65]:
y_pred2 = softmax_model2.predict(X2_test)
print(y_pred2)

[0 0 1 ... 1 0 1]


In [66]:
X3=data3.drop('issue_3',axis=1)
y3=data3['issue_3']
X3_train,X3_test,y3_train,y3_test=train_test_split(X3,y3,test_size=0.3,random_state=0)
softmax_model3 = LogisticRegression(multi_class='multinomial', solver='lbfgs')
softmax_model3.fit(X3_train, y3_train)

C:\Users\HRITHIK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [67]:
y_pred3 = softmax_model3.predict(X3_test)
print(y_pred3)

[0 0 2 ... 2 0 2]


In [68]:
X4=data4.drop('issue_4',axis=1)
y4=data4['issue_4']
X4_train,X4_test,y4_train,y4_test=train_test_split(X4,y4,test_size=0.3,random_state=0)
softmax_model4 = LogisticRegression(multi_class='multinomial', solver='lbfgs')
softmax_model4.fit(X4_train, y4_train)

C:\Users\HRITHIK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [69]:
y_pred4 = softmax_model4.predict(X4_test)
print(y_pred4)

[0 0 0 ... 0 0 0]


## Naive Bayes

In [70]:
from sklearn.naive_bayes import GaussianNB

In [71]:
naive_bayes = GaussianNB()
naive_bayes.fit(X1_train , y1_train)

GaussianNB()

In [73]:
#Predict on test data
y_predicted1 = naive_bayes.predict(X1_test)
print(y_predicted1)

[5 7 8 ... 5 7 8]


In [74]:
naive_bayes = GaussianNB()
naive_bayes.fit(X2_train , y2_train)

GaussianNB()

In [75]:
#Predict on test data
y_predicted2 = naive_bayes.predict(X2_test)
print(y_predicted2)

[1 0 1 ... 1 0 3]


In [76]:
naive_bayes = GaussianNB()
naive_bayes.fit(X3_train , y3_train)

GaussianNB()

In [77]:
#Predict on test data
y_predicted3 = naive_bayes.predict(X3_test)
print(y_predicted3)

[2 0 2 ... 2 0 1]


In [78]:
naive_bayes = GaussianNB()
naive_bayes.fit(X4_train , y4_train)

GaussianNB()

In [79]:
#Predict on test data
y_predicted4 = naive_bayes.predict(X4_test)
print(y_predicted4)

[0 0 0 ... 0 0 0]


## Decision tree classifier

In [80]:
from sklearn.tree import DecisionTreeClassifier

In [81]:
tree_clf1 = DecisionTreeClassifier(criterion='entropy',max_depth=2)
tree_clf1.fit(X1_train , y1_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [82]:
#Predict on test data
y_pred_dt1 = tree_clf1.predict(X1_test)
print(y_pred_dt1)

[ 4 11  5 ...  5  7  5]


In [83]:
tree_clf2 = DecisionTreeClassifier(criterion='entropy',max_depth=2)
tree_clf2.fit(X2_train , y2_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [84]:
#Predict on test data
y_pred_dt2 = tree_clf2.predict(X2_test)
print(y_pred_dt2)

[0 0 1 ... 1 0 1]


In [85]:
tree_clf3 = DecisionTreeClassifier(criterion='entropy',max_depth=2)
tree_clf3.fit(X3_train , y3_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [86]:
y_pred_dt3 = tree_clf3.predict(X3_test)
print(y_pred_dt3)

[0 0 2 ... 2 0 2]


In [87]:
tree_clf4 = DecisionTreeClassifier(criterion='entropy',max_depth=2)
tree_clf4.fit(X4_train , y4_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [88]:
y_pred_dt4 = tree_clf4.predict(X4_test)
print(y_pred_dt4)

[0 0 0 ... 0 0 0]


## XGBoost Classifier

In [90]:
pip install xgboost

     ---------------------------------------- 99.7/99.7 MB 5.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [91]:
import xgboost as xgb

In [92]:
xgb_classifier1 = xgb.XGBClassifier(
    objective='multi:softmax',  # For multiclass classification
    num_class=len(np.unique(df['issue_1'])),  # Number of classes
    max_depth=3,  # Maximum tree depth
    learning_rate=0.1,  # Learning rate
    n_estimators=100  # Number of boosting rounds
)

In [93]:
xgb_classifier1.fit(X1_train, y1_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None, num_class=18,
              num_parallel_tree=None, ...)

In [95]:
y_pred_xg1 = xgb_classifier1.predict(X1_test)
print(y_pred_xg1)

[4 7 5 ... 5 7 5]


In [96]:
xgb_classifier2 = xgb.XGBClassifier(
    objective='multi:softmax',  # For multiclass classification
    num_class=len(np.unique(df['issue_2'])),  # Number of classes
    max_depth=3,  # Maximum tree depth
    learning_rate=0.1,  # Learning rate
    n_estimators=100  # Number of boosting rounds
)
xgb_classifier2.fit(X2_train, y2_train)
y_pred_xg2 = xgb_classifier2.predict(X2_test)
print(y_pred_xg2)

[0 0 1 ... 0 0 1]


In [98]:
xgb_classifier3 = xgb.XGBClassifier(
    objective='multi:softmax',  # For multiclass classification
    num_class=len(np.unique(df['issue_3'])),  # Number of classes
    max_depth=3,  # Maximum tree depth
    learning_rate=0.1,  # Learning rate
    n_estimators=100  # Number of boosting rounds
)
xgb_classifier3.fit(X3_train, y3_train)
y_pred_xg3 = xgb_classifier3.predict(X3_test)
print(y_pred_xg3)

[0 0 2 ... 0 0 2]


In [99]:
xgb_classifier4 = xgb.XGBClassifier(
    objective='multi:softmax',  # For multiclass classification
    num_class=len(np.unique(df['issue_4'])),  # Number of classes
    max_depth=3,  # Maximum tree depth
    learning_rate=0.1,  # Learning rate
    n_estimators=100  # Number of boosting rounds
)
xgb_classifier4.fit(X4_train, y4_train)
y_pred_xg4 = xgb_classifier4.predict(X4_test)
print(y_pred_xg4)

[0 0 0 ... 0 0 0]


## Model evaluation

In [100]:
from sklearn.metrics import accuracy_score

In [117]:
issue1_metrics=[]
issue2_metrics=[]
issue3_metrics=[]
issue4_metrics=[]

In [119]:
# Calculate accuracy
accuracy1 = accuracy_score(y1_test, y_pred1)
accuracy2 = accuracy_score(y1_test, y_predicted1)
accuracy3 = accuracy_score(y1_test, y_pred_dt1)
accuracy4 = accuracy_score(y1_test, y_pred_xg1)

issue1_metrics=[accuracy1,accuracy2,accuracy3,accuracy4]

In [120]:
accuracy1 = accuracy_score(y1_test, y_pred2)
accuracy2 = accuracy_score(y1_test, y_predicted2)
accuracy3 = accuracy_score(y1_test, y_pred_dt2)
accuracy4 = accuracy_score(y1_test, y_pred_xg2)

issue2_metrics=[accuracy1,accuracy2,accuracy3,accuracy4]

In [121]:
accuracy1 = accuracy_score(y1_test, y_pred3)
accuracy2 = accuracy_score(y1_test, y_predicted3)
accuracy3 = accuracy_score(y1_test, y_pred_dt3)
accuracy4 = accuracy_score(y1_test, y_pred_xg3)

issue3_metrics=[accuracy1,accuracy2,accuracy3,accuracy4]

In [122]:
accuracy1 = accuracy_score(y1_test, y_pred4)
accuracy2 = accuracy_score(y1_test, y_predicted4)
accuracy3 = accuracy_score(y1_test, y_pred_dt4)
accuracy4 = accuracy_score(y1_test, y_pred_xg4)

issue4_metrics=[accuracy1,accuracy2,accuracy3,accuracy4]

In [127]:
final=[sum(issue1_metrics)/4,sum(issue2_metrics)/4,sum(issue3_metrics)/4,sum(issue4_metrics)/4]

In [128]:
d={"Classfication model":["Softmax","Naive bayes","Decision tree","XGBoost"],"accuracy":final}

In [129]:
pd.DataFrame(d)

Classfication model  accuracy
0             Softmax  0.712106
1         Naive bayes  0.032698
2       Decision tree  0.012673
3             XGBoost  0.021192

# Conclusion

## The reason behind training the model separately for issues because the text preprocessing has been resulted in creation of separate features for each issue. The product feature is the output feature and it contains multiple categories. So the output variables should be splitted and trained

# Among the 4 models the softmax classifier gives the better accuracy